version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - inception-bridge-net
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "mysqladmin ping && mysqladmin variables | grep skip_networking | grep -q OFF",
        ]
      interval: 3s
      timeout: 3s
      retries: 5

  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception-bridge-net
    environment:
      CERT_PEM: ${CERT_PEM}
      KEY_PEM: ${KEY_PEM}

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception-bridge-net
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mariadb
      WP_DOMAIN: ${WP_DOMAIN}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_EMAIL: ${WP_EMAIL}
      USER_NAME: ${USER_NAME}
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}

volumes:
  mariadb_data:
  # write volume setting to mount /Users/yourname/wordpress_files to /var/www/html
  wordpress_files:
    driver_opts:
      type: none
      device: /Users/yourname/wordpress_files
      o: bind

networks:
  inception-bridge-net:
    driver: bridge
