# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dowon <dowon@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/25 17:20:30 by dowon             #+#    #+#              #
#    Updated: 2023/05/25 17:20:31 by dowon            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

d_list:
	make -C $@

ft_printf:
	make -C $@

libft:
	make -C $@

smart_ptr:
	make -C $@

.PHONY: d_list ft_printf libft smart_ptr